"""empty message

Revision ID: 1ea73ec76c33
Revises: 9cbc1a40da13
Create Date: 2026-04-23 13:39:41.556730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ea73ec76c33"
down_revision: Union[str, Sequence[str], None] = "9cbc1a40da13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "reviews", ["review_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="unique")
    # ### end Alembic commands ###
