"""empty message

Revision ID: 5a933d38398d
Revises: c749426cf628
Create Date: 2025-11-25 13:10:20.913076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a933d38398d"
down_revision: Union[str, Sequence[str], None] = "c749426cf628"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author_ciema",
        sa.Column("film_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.author_id"],
        ),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["films.film_id"],
        ),
        sa.PrimaryKeyConstraint("film_id", "author_id"),
    )
    op.create_table(
        "fans_user",
        sa.Column("film_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["films.film_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("film_id", "user_id"),
    )
    op.create_table(
        "film_actor",
        sa.Column("film_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.actor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["films.film_id"],
        ),
        sa.PrimaryKeyConstraint("film_id", "actor_id"),
    )
    op.add_column("actors", sa.Column("actor_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "actors", "patronymic", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_unique_constraint(None, "actors", ["actor_id"])
    op.drop_column("actors", "id")
    op.add_column("authors", sa.Column("author_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "authors", "patronymic", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "authors", "bio", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_unique_constraint(None, "authors", ["author_id"])
    op.drop_column("authors", "id")
    op.add_column("coments", sa.Column("coment_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, "coments", ["coment_id"])
    op.drop_constraint(
        op.f("coments_user_id_fkey"), "coments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("coments_film_id_fkey"), "coments", type_="foreignkey"
    )
    op.create_foreign_key(None, "coments", "films", ["film_id"], ["film_id"])
    op.create_foreign_key(None, "coments", "users", ["user_id"], ["user_id"])
    op.drop_column("coments", "id")
    op.add_column("films", sa.Column("film_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "films", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "films", "release_date", existing_type=sa.DATE(), nullable=True
    )
    op.create_unique_constraint(None, "films", ["film_id"])
    op.drop_column("films", "id")
    op.drop_column("films", "estimation")
    op.add_column(
        "ratingfilms", sa.Column("rating_id", sa.Uuid(), nullable=False)
    )
    op.create_unique_constraint(None, "ratingfilms", ["rating_id"])
    op.drop_constraint(
        op.f("ratingfilms_film_id_fkey"), "ratingfilms", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("ratingfilms_user_id_fkey"), "ratingfilms", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ratingfilms", "films", ["film_id"], ["film_id"]
    )
    op.create_foreign_key(
        None, "ratingfilms", "users", ["user_id"], ["user_id"]
    )
    op.drop_column("ratingfilms", "id")
    op.add_column("users", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, "users", ["user_id"])
    op.drop_column("users", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "user_id")
    op.add_column(
        "ratingfilms",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "ratingfilms", type_="foreignkey")
    op.drop_constraint(None, "ratingfilms", type_="foreignkey")
    op.create_foreign_key(
        op.f("ratingfilms_user_id_fkey"),
        "ratingfilms",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("ratingfilms_film_id_fkey"),
        "ratingfilms",
        "films",
        ["film_id"],
        ["id"],
    )
    op.drop_constraint(None, "ratingfilms", type_="unique")
    op.drop_column("ratingfilms", "rating_id")
    op.add_column(
        "films",
        sa.Column(
            "estimation", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "films",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "films", type_="unique")
    op.alter_column(
        "films", "release_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "films", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("films", "film_id")
    op.add_column(
        "coments",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "coments", type_="foreignkey")
    op.drop_constraint(None, "coments", type_="foreignkey")
    op.create_foreign_key(
        op.f("coments_film_id_fkey"), "coments", "films", ["film_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("coments_user_id_fkey"), "coments", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "coments", type_="unique")
    op.drop_column("coments", "coment_id")
    op.add_column(
        "authors",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "authors", type_="unique")
    op.alter_column(
        "authors", "bio", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "authors", "patronymic", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("authors", "author_id")
    op.add_column(
        "actors",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "actors", type_="unique")
    op.alter_column(
        "actors", "patronymic", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("actors", "actor_id")
    op.drop_table("film_actor")
    op.drop_table("fans_user")
    op.drop_table("author_ciema")
    # ### end Alembic commands ###
